### PR TITLE
fix suffix for live editor

### LINKED ISSUE #6114: Contact Form Submission - Website Bug (General - Resources: Learning to Code)
Someone submitted the contact form!

**URL**: https://usaco.guide/general/resources-learning-to-code?lang=cpp
**Module**: General - Resources: Learning to Code
**Topic**: Website Bug
**Message**: 
"Edit this page" is broken, it brings me to

https://usaco.guide/editor?filepath=content/content/1_General/Learning_to_Code.mdx

which doesn't exist.

### PR DESCRIPTION
**Pull request by bqi343**
fixes for live editor and problem suggestions

Closes #6114

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

---

<a href="https://app.devin.ai/review/cpinitiative/usaco-guide/pull/6115" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

**Comment by bqi343** [comment]
Problem suggestion modal still bugged (and doesn't submit either).

Screenshot 2026-04-09 at 7 55 25 PM

**Comment by bqi343** [comment]
@emhgit for the issue of two cancel buttons rendering simultaneously, I believe you introduced a relevant change.

https://github.com/cpinitiative/usaco-guide/blob/master/src/components/ProblemSuggestionModal.tsx

previously there was only one cancel: https://github.com/cpinitiative/usaco-guide/blob/83af56f46d00f77299c16461ec36d888d6467ccb/src/components/ProblemSuggestionModal.tsx

File: src/functions/src/submitProblemSuggestion.ts [hunk 1]
```diff
@@ -158,7 +158,7 @@ const submitProblemSuggestion = functions.https.onCall(async request => {
   });
 
   const oldFileDataReq = await githubAPI.get(
```
Comment (bqi343) [inline src/functions/src/submitProblemSuggestion.ts:160]: TODO: figure out how to deploy functions ...

Comment (emhgit) [reply src/functions/src/submitProblemSuggestion.ts:160]: i created a [PR](https://github.com/cpinitiative/usaco-guide/pull/6116) that removes the duplicate button indicating "cancel". (i also noticed that the editor link wasn't on the mobile navbar, so i added that as well). i don't have authentication to deploy firebase functions, but i believe you can using:

```
cd src/functions
firebase deploy --only functions:submitProblemSuggestion
```

**Review by emhgit — APPROVED** [review]

File: src/functions/src/submitProblemSuggestion.ts (hunk 1 above)
Comment (bqi343) [reply src/functions/src/submitProblemSuggestion.ts:160]: that used to work for me but now it isn't, I guess something being too old is preventing new functions from being deployed :shrug:

updated PR to no longer require updating the function

File: src/components/markdown/ProblemsList/SuggestProblemRow.tsx [hunk 2]
```diff
@@ -1,12 +1,10 @@
-import { globalHistory } from '@reach/router';
 import { useContext } from 'react';
 import { EditorContext } from '../../../context/EditorContext';
 import ProblemSuggestionModalContext from '../../../context/ProblemSuggestionModalContext';
 
 export default function SuggestProblemRow({ listName }: { listName: string }) {
   const context = useContext(ProblemSuggestionModalContext);
   const { inEditor } = useContext(EditorContext);
-  const path = globalHistory.location.pathname || '';
```
Comment (bqi343) [inline src/components/markdown/ProblemsList/SuggestProblemRow.tsx:9]: unused
