### PR TITLE
(try to) fix user progress on modules / problems deletion issue

### LINKED ISSUE #3396: User problem data getting erased
Hi, I'm the user that submitted the issue #3389.
I saw bqi343's comment on my issue.
image
Does this imply that the same problem had happened before?
If so, can you guys give me the link of the previous issue or maybe tell me how the issue got solved?
Thank you.

### PR DESCRIPTION
**Pull request by thecodingwizard**
closes #3396, #3425

I don't actually know if this works lol, but hopefully if data is lost we will only lose the data on that particular problem / module progress which is fine.

I think other places `setDoc` is used include daily # of pageviews, but I don't think it's that bad if that data is lost.

The scary part of using `updateData` is if the doc doesn't exist then it will crash and die. But this would only happen when the user account is first created, and I think once the account is created data is written anyway...

### CODE REVIEW

**Comment by thecodingwizard** [comment]
Please help test!! Otherwise I will just randomly merge this at some point :)

File: src/components/markdown/ResourceStatusCheckbox.tsx [hunk 1]
```diff
@@ -6,6 +6,7 @@ import 'tippy.js/themes/light.css';
 import ConfettiContext from '../../context/ConfettiContext';
 import { useDarkMode } from '../../context/DarkModeContext';
 import MarkdownLayoutContext from '../../context/MarkdownLayoutContext';
+import { replaceIllegalFirebaseCharacters } from '../../context/UserDataContext/properties/userProgressOnResources';
```
Comment (bqi343) [inline src/components/markdown/ResourceStatusCheckbox.tsx:9]: mind explaining the changes you made?

File: src/context/UserDataContext/properties/userProgressOnResources.ts [hunk 2]
```diff
@@ -52,30 +56,26 @@ export default class UserProgressOnResourcesProperty extends UserDataPropertyAPI
...
-            setDoc(
-              this.firebaseUserDoc,
-              {
-                [this.progressStorageKey]: {
-                  [problemId]: status,
-                },
-              },
-              { merge: true }
-            );
+            updateDoc(this.firebaseUserDoc, {
```
Comment (bqi343) [inline src/context/UserDataContext/properties/userProgressOnResources.ts:69]: what's the difference?

Comment (thecodingwizard) [reply src/context/UserDataContext/properties/userProgressOnResources.ts:69]: Actually, I realized there is no difference 🤡 

I thought `setDoc` might not work with nested objects but actually that is incorrect (it does work with nested objects). But I think `arrayUnion` only works with `updateDoc` (but I could be wrong)

File: src/components/markdown/ResourceStatusCheckbox.tsx (hunk 1 above)
Comment (thecodingwizard) [reply src/components/markdown/ResourceStatusCheckbox.tsx:9]: I read the problem progress from local storage every time before writing to Firebase, changed `setDoc` to `updateDoc`, and used `arrayUnion` to add an element into the progress array rather than override the entire array. Reasoning for each change:

- local storage: this shouldn't do anything, especially after the other two changes. (In fact I am like pretty sure this change does nothing)
- setDoc => updateDoc: this allows us to use `arrayUnion`. It's possible that a poor internet connection could cause user activity array to be overwritten by an outdated user activity array (this would be fixed by arrayUnion), but this doesn't explain why user problem progress is being lost.

**Comment by thecodingwizard** [comment]
I think it's possible to write a firebase function that runs every time a user document changes. If we do this, we can check to see if the user progress on problems was being overwritten and try to reproduce the issue / debug from there. It seems like a nontrivial amount of work though :/

**Comment by bqi343** [comment]
Screen Shot 2023-03-04 at 3 58 47 PM

this happens when I try to mark problems on the deployed URL for the first time. I can't reproduce it though ...

File: src/components/markdown/ResourceStatusCheckbox.tsx (hunk 1 above)
Comment (bqi343) [reply src/components/markdown/ResourceStatusCheckbox.tsx:9]: ok, then should we leave the issue open?

**Comment by thecodingwizard** [comment]
@bqi343 can you check the dev console?

**Comment by thecodingwizard** [comment]
Also can you reproduce this issue in the latest commit? https://usaco-guide-git-fix-data-deletion-cpinitiative.vercel.app/

there was a bug but I fixed it in the last commit I think

**Comment by bqi343** [comment]
whoops I was pressing the wrong URL, seems okay in latest

File: src/components/markdown/ResourceStatusCheckbox.tsx (hunk 1 above)
Comment (thecodingwizard) [reply src/components/markdown/ResourceStatusCheckbox.tsx:9]: Probably. Maybe we can make one mega issue for reporting lost data and pin it?

Comment (bqi343) [reply src/components/markdown/ResourceStatusCheckbox.tsx:9]: ok

**Review by bqi343 — APPROVED** [review]
